-- Table Creation

create table public."League" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  admin_id uuid null default gen_random_uuid (),
  constraint League_pkey primary key (id),
  constraint League_admin_id_fkey foreign KEY (admin_id) references auth.users (id)
) TABLESPACE pg_default;

create table public."LeagueYear" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  league_id bigint not null,
  year integer not null,
  constraint LeagueYear_pkey primary key (id),
  constraint LeagueYear_league_id_fkey foreign KEY (league_id) references "League" (id)
) TABLESPACE pg_default;

create table public."LeagueYearPlayer" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  league_year_id bigint not null,
  nickname text null,
  user_id uuid not null,
  constraint LeagueYearPlayer_pkey primary key (id),
  constraint LeagueYearPlayer_league_year_id_fkey foreign KEY (league_year_id) references "LeagueYear" (id),
  constraint LeagueYearPlayer_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;

create table public."Team" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  seed integer not null,
  year integer not null,
  wins integer not null default 0,
  constraint Team_pkey primary key (id)
) TABLESPACE pg_default;

create table public."LeagueYearTeam" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  team_id bigint not null,
  points_per_win integer not null default 1,
  player_id bigint null,
  constraint LeagueYearTeam_pkey primary key (id),
  constraint LeagueYearTeam_player_id_fkey foreign KEY (player_id) references "LeagueYearPlayer" (id),
  constraint LeagueYearTeam_team_id_fkey foreign KEY (team_id) references "Team" (id)
) TABLESPACE pg_default;

create table public."BracketGame" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  year integer not null,
  game_number integer not null,
  team_one bigint null,
  team_two bigint null,
  constraint BracketGame_pkey primary key (id),
  constraint BracketGame_team_one_fkey foreign KEY (team_one) references "Team" (id),
  constraint BracketGame_team_two_fkey foreign KEY (team_two) references "Team" (id)
) TABLESPACE pg_default;